# Custom Language File for Launcher Customizer

[ejs.app]
title = "Hobbitcraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://hobbitcraft.cc/invite"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE HOBBITCRAFT LAUNCHER"
welcomeDescription = ""
welcomeDescCTA = "cta text"
